### ISSUE TITLE
Add pokemon types

### ISSUE THREAD

**Issue by BrunnerLivio** [BrunnerLivio/pokemongo-json-pokedex#18]
## Metadata 
JSON Key: typeEffective
Outputfile: pokemon-type.json
**Unanswered questions:**
- attackScalar : What is this attribute?
- Does the weaknesses and strengths of a type differ in Pokemon Go from the original Pokemon?

## Example
```JSON
{
	"templateId": "POKEMON_TYPE_ROCK",
	"typeEffective": {
		"attackScalar": [1, 0.8, 1.25, 1, 0.8, 1, 1.25, 1, 0.8, 1.25, 1, 1, 1, 1, 1.25, 1, 1, 1],
		"attackType": "POKEMON_TYPE_ROCK"
	}
}
```

## Expected Output
```JavaScript
{
    "id":  "POKEMON_TYPE_GROUND",
    "name": "Ground",
    "damage_relations": {
        "no_damage_to": [{
            "name": "flying",
            "url": "http://pokeapi.co/api/v2/type/3/"
        }],
        "half_damage_to": [{
            "name": "bug",
            "url": "http://pokeapi.co/api/v2/type/7/"
        }],
        "double_damage_to": [{
            "name": "poison",
            "url": "http://pokeapi.co/api/v2/type/4/"
        }],
        "no_damage_from": [{
            "name": "electric",
            "url": "http://pokeapi.co/api/v2/type/13/"
        }],
        "half_damage_from": [{
            "name": "poison",
            "url": "http://pokeapi.co/api/v2/type/4/"
        }],
        "double_damage_from": [{
            "name": "water",
            "url": "http://pokeapi.co/api/v2/type/11/"
        }]
    }
}
```

**Comment by proegssilb** [comment]
I assume this is to generate a types.json file with labelled info on which types are good against which other types?

**Comment by BrunnerLivio** [comment]
@proegssilb Yes. Upated the description

**Comment by proegssilb** [comment]
Guess I have some incentive to work on this now: https://github.com/proegssilb/pokemon-types

**Comment by dominicbarnes** [comment]
I was working on adding this, but I'm blocked on BrunnerLivio/pokemongo-game-master#18. The `attack_scalar` array is in order and the indices are based on the raw numeric IDs that we don't have available atm. (you can see my branch [here](https://github.com/BrunnerLivio/pokemongo-json-pokedex/compare/master...dominicbarnes:type))

**Comment by vfcp** [comment]
Created PR #40 based on @dominicbarnes branch with the right order for the types
