### ISSUE TITLE
Missing Moves

### ISSUE THREAD

**Issue by Aethios** [BrunnerLivio/pokemongo-json-pokedex#28]
Your simplified JSON file looks great. I'm trying to use the raw files as a library for a Pokemon Go Discord bot with Pokedex commands, but certain moves are missing from move.json and it's causing errors. The moves that are missing, in no particular order:

Air Slash
Bullet Seed
Crunch
Outrage
Dragon Tail
Hidden Power
Struggle Bug

There may be more but these were the ones I stumbled into naturally.

**Comment by proegssilb** [comment]
Can you confirm whether these are legacy moves or not? At least some of them shouldn't be from guesswork, but wanted to double-check...

**Comment by Aethios** [comment]
They are not legacy. The Pokemon throwing errors due to these missing moves
are doing so because they are listed in the GAME_MASTER file as being able
to learn these moves right now. The missing moves appear in the GAME_MASTER
files, including the file you've used here. I even tried downloading your
script and using a freshly updated GAME_MASTER from another source, with
the same result. The issue lies within the script, as it appears to be
ignoring these moves for some unknown reason.

**Comment by Aethios** [comment]
For completeness, I'll give an example.

`{
    "templateId": "V0255_MOVE_AIR_SLASH_FAST",
    "moveSettings": {
      "movementId": "AIR_SLASH_FAST",
      "animationId": 4,
      "pokemonType": "POKEMON_TYPE_FLYING",
      "power": 14.0,
      "accuracyChance": 1.0,
      "staminaLossScalar": 0.01,
      "trainerLevelMin": 1,
      "trainerLevelMax": 100,
      "vfxName": "air_slash_fast",
      "durationMs": 1200,
      "damageWindowStartMs": 1000,
      "damageWindowEndMs": 1200,
      "energyDelta": 10
    }
  },`

This is code taken directly from https://github.com/BrunnerLivio/pokemongo-game-master/blob/master/versions/latest/GAME_MASTER.json and yet this move does not appear anywhere in move.json.

**Comment by proegssilb** [comment]
The legacy moves being absent is something that came up before, so I wanted to make sure we didn't have a duplicate issue. The moves you listed aren't legacy, so this isn't a duplicate issue.

**Comment by BrunnerLivio** [comment]
Thanks a lot, good catch @Aethios !

The problem was in the *.parser file. I actually think it was an error from TypeScript / NodeJS. But not 100% sure yet. 

As you can see in the [pull request](https://github.com/BrunnerLivio/pokemongo-json-pokedex/pull/29/files), the only thing the bug was causing, creating the instance of `RegExp` when [assigning to the attribute](https://github.com/BrunnerLivio/pokemongo-json-pokedex/pull/29/files#diff-667e8a4888e96c6e714e1f30e59e9ef2L6), [instead of creating the instance inside the ](https://github.com/BrunnerLivio/pokemongo-json-pokedex/pull/29/files#diff-667e8a4888e96c6e714e1f30e59e9ef2R9)`isItemTemplateMove`-Method.

**Comment by Aethios** [comment]
Just a heads up: While the primary issue with moves missing has been resolved, Struggle (and probably any other move that generates or consumes 0 energy) does not have an energyDelta attribute. While this particular issue is fixed with a slightly modified bit of code, it's probably best to keep the JSON structure consistent between moves to avoid unforeseen behavior in scripts that utilize it.

**Comment by proegssilb** [comment]
Just an FYI, @Aethios, I normally consider it to be good etiquette to keep issues focused on a single topic, and open new issues for different bugs. I'll open a new one for what you just described imminently.
