### ISSUE TITLE
BaseFleeRate vs BaseCaptureRate

### ISSUE THREAD

**Issue by Aethios** [BrunnerLivio/pokemongo-json-pokedex#32]
BaseFleeRate is in the data for every species, but BaseCaptureRate is not. Is there a reason this was not included? Can it be added? They're literally right next to each other in the GAME_MASTER JSON files.

**Comment by BrunnerLivio** [comment]
Yep, probably was forgotten. Don't see why we should not implement this. 

Will add the attribute as soon a possible. 

Thanks for reporting, good catch!
