### ISSUE TITLE
Refactor Pokemon structure

### ISSUE THREAD

**Issue by moriakaice** [BrunnerLivio/pokemongo-json-pokedex#47]
Based on my thoughts from here: https://github.com/BrunnerLivio/pokemongo-json-pokedex/pull/42#discussion_r158943129

Current evolution implementation was done to satisfy requirements in https://github.com/BrunnerLivio/pokemongo-json-pokedex/issues/20 However, after the implementation and as an afterthought, I want to propose the Pokemon structure to be refactored.

Proposed changes:
* make Pokemon evolution costs a direct property of a Pokemon.
Example:
```
{
  "dex": 230,
  "id": "KINGDRA",
  ...
  "costToEvolve": {
    "candyCost": 100,
    "evolutionItem": {
      "id": "ITEM_DRAGON_SCALE",
      "name": "Dragon Scale"
    }
  }
}
```
Motivation:
Current Pokemon evolution cost does not belong to `futureEvolutions` logically, as it's not a "next step" evolution, but the cost of evolving previous Pokemon into current one. Also, Pokemon GO doesn't have different methods of evolving one Pokemon into another, so this doesn't need to be an array of any kind.
Alternative name for the property could be `evolutionCost`, but this can be misleading.

* simplify `futureEvolutions` to avoid data duplication.
Example:
* current situation:
```
"futureEvolutions": {
  "futureEvolutions": [
    {
      "futureEvolutions": [],
      "name": "Kingdra",
      "id": "KINGDRA",
      "candyCost": 100,
      "evolutionItem": {
        "id": "ITEM_DRAGON_SCALE",
        "name": "Dragon Scale"
      }
    }
  ],
  "name": "Seadra",
  "id": "SEADRA",
  "candyCost": 25
}
```
* proposed state:
```
"futureEvolutions": [
  {
    "futureEvolutions": [],
    "name": "Kingdra",
    "id": "KINGDRA",
    "candyCost": 100,
    "evolutionItem": {
      "id": "ITEM_DRAGON_SCALE",
      "name": "Dragon Scale"
    }
  }
]
```
Motivation:
Suggested changes simplify the structure, remove the need to do an awkward `.futureEvolutions.futureEvolutions` to get "real" evolutions of a Pokemon, as well as remove some data duplication.

**Comment by proegssilb** [comment]
I'll support what's described here when you can show me how your proposal handles both Eevee's/Tyrogue's future evolutions and Bulbasaur's future evolutions.

**Comment by moriakaice** [comment]
```
{
  "dex": 1,
  "id": "BULBASAUR",
  "name": "Bulbasaur",
  "futureEvolutions": [
    {
      "futureEvolutions": [
        {
          "futureEvolutions": [],
          "name": "Venusaur",
          "id": "VENUSAUR",
          "candyCost": 100
        }
      ],
      "name": "Ivysaur",
      "id": "IVYSAUR",
      "candyCost": 25
    }
  ]
}
```

```
{
  "dex": 236,
  "id": "TYROGUE",
  "name": "Tyrogue",
  "futureEvolutions": [
    {
      "futureEvolutions": [],
      "name": "Hitmonlee",
      "id": "HITMONLEE",
      "candyCost": 25
    },
    {
      "futureEvolutions": [],
      "name": "Hitmonchan",
      "id": "HITMONCHAN",
      "candyCost": 25
    },
    {
      "futureEvolutions": [],
      "name": "Hitmontop",
      "id": "HITMONTOP",
      "candyCost": 25
    }
  ]
}
```

If that's what you're asking for. Basically, follow the same structure as main Pokemon entry, but without most of the details not associated with the evo cost.

**Comment by proegssilb** [comment]
For comparison (pulled from master): ```
{
        "dex": 236,
        ...
        "id": "TYROGUE",
        "name": "Tyrogue",
        ....
        "maxCP": 404,
        "futureEvolutions": {
            "futureEvolutions": [
                {
                    "futureEvolutions": [],
                    "name": "Hitmonlee",
                    "id": "HITMONLEE",
                    "candyCost": 25
                },
                {
                    "futureEvolutions": [],
                    "name": "Hitmonchan",
                    "id": "HITMONCHAN",
                    "candyCost": 25
                },
                {
                    "futureEvolutions": [],
                    "name": "Hitmontop",
                    "id": "HITMONTOP",
                    "candyCost": 25
                }
            ],
            "name": "Tyrogue",
            "id": "TYROGUE"
        }
    },
```

The biggest difference I'm seeing is that you're removing a level of the tree, and cutting straight to an array. Without an example, I had a hard time pickup up on that.

This is, of course, a breaking change, but as far as I know, that's not a big deal.

**Comment by BrunnerLivio** [comment]
I'm on board with that proposal. 

> This is, of course, a breaking change, but as far as I know, that's not a big deal.

Should not be a big deal. We just release the next version as 3.0.0

**Comment by BrunnerLivio** [comment]
My additional proposal:

**Join futureEvolutions, pastEvolutions together in a object called "evolution"**
It is more consistent with the structure like `pokemon.encounter`.

**Rename futureEvolutions & pastEvolutions to futureBranches and pastBranches**
It makes more sense to call it branches instead of evolutions, because you do not actually access "all" future evolutions, but just the upper branch. 

It would still be understandable thanks to the first proposal, because it is in the context pokemon.**evolution**.futureBranches.

**Remove nextEvolutionBranches**
I don't think this is needed anymore. If you need the next evolution branch just use `pokemon.evolution.futureBranches`. 

**Wrap costToEvolve inside evolution**
Self explanatory. 

New Ivysaur: 
```JSON
{
    "dex": 2,
    "name": "Ivysaur",
    [...]
    "evolution": {
        "costToEvolve": {
            "candyCost": 25
        },
        "futureBranches": [
            {
                "futureBranches": [],
                "name": "Venusaur",
                "id": "VENUSAUR",
                "costToEvolve": {
                    "candyCost": 100
                }
            }
        ],
        "pastBranches": [
            {
                "name": "Bulbasaur",
                "id": "BULBASAUR"
            }
        ]
    }
}
```

Currently: 
```JSON
{
    "dex": 2,
    "name": "Ivysaur",
    [...]
    "nextEvolutionBranches": [
        {
            "name": "Venusaur",
            "id": "VENUSAUR",
            "candyCost": 100
        }
    ],
    "pastEvolutions": [
        {
            "name": "Bulbasaur",
            "id": "BULBASAUR"
        }
    ],
    "futureEvolutions": {
        "futureEvolutions": [
            {
                "futureEvolutions": [],
                "name": "Venusaur",
                "id": "VENUSAUR",
                "candyCost": 100
            }
        ],
        "name": "Ivysaur",
        "id": "IVYSAUR",
        "candyCost": 25
    }
}
```
