### ISSUE TITLE
Please include Pokemon number as well

### ISSUE THREAD

**Issue by henrykuijpers** [BrunnerLivio/pokemongo-json-pokedex#49]
Please include pokemon number as well

**Comment by BrunnerLivio** [comment]
This feature is already included. When you open [output/pokemon.json](https://github.com/BrunnerLivio/pokemongo-json-pokedex/blob/master/output/pokemon.json), you can see the attribute `dex` is the pokemon "number". More information on the [model documentation](https://github.com/BrunnerLivio/pokemongo-json-pokedex/blob/master/.github/model.md#pokemon)
